services:
  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: app
    ports:
      - "3002:3002"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ../data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
